/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import mdx from "@paulislava/strapi-mdx-editor/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import sortableEntries from "strapi-plugin-sortable-entries/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    mdx: mdx,
    graphql: graphql,
    "users-permissions": usersPermissions,
    "sortable-entries": sortableEntries,
  },
});
